theme: jekyll-theme-minimal
title: S.c.o.t.t.
description: Structure Canonisation using Ordered-Tree Translation
logo: https://raw.githubusercontent.com/theplatypus/test-pages/master/docs/scott2.png
show_downloads: "true" 
